services:
  - type: web
    name: medplat-chatbot
    env: docker
    repo: https://github.com/parharti/med_plat  # ğŸ” Replace this
    region: oregon
    plan: free

    dockerfilePath: ./Dockerfile  # Or change if your Dockerfile is elsewhere

    envVars:
      - key: PORT
        value: 5005

    healthCheckPath: /status
    autoDeploy: true
